### ISSUE TITLE
数据集有关问题

### ISSUE THREAD

**Issue by cc13qq** [TencentYoutuResearch/Adv-Makeup#12]
您好，我想在lfw数据集上复现adv-makeup，以及根据LADN生成更多对抗样本，请问数据集的landmark的pickle文件是怎样生成的？我观察到您把LADN的图片都裁剪到600x600，请问是怎样裁剪的？谢谢

**Comment by yubangji123** [comment]
你好，这个可以使用MTCNN对人脸图片进行align和crop

**Comment by cc13qq** [comment]
感谢回答。那请问landmark是用什么生成的呢？

**Comment by yubangji123** [comment]
landmark你可以找一些facealignment的工具来获取

**Comment by computerAItest** [comment]
> 
请问你实现了，我也有问题
