### ISSUE TITLE
各个模型FAR的计算方式

### ISSUE THREAD

**Issue by junyizeng** [TencentYoutuResearch/Adv-Makeup#13]
您好，我想要在当前模型的基础上增加预训练的人脸识别模型观察攻击效果是否提升，想请问一下论文中各个人脸识别模型的FAR的计算方式，时使用的什么数据集进行计算的？数据量是多少？

**Comment by yubangji123** [comment]
在LFW上面计算的，FAR计算方式在很多人脸识别的论文和project中都有，你可以去搜一下

**Comment by junyizeng** [comment]
好的，谢谢您的回复。
