### ISSUE TITLE
论文实验设置

### ISSUE THREAD

**Issue by junyizeng** [TencentYoutuResearch/Adv-Makeup#14]
研发人员您好，在根据论文中的实验设置描述复现文中的数字攻击的实验一时对实验一中的实验设置有一些疑惑，想请教以下问题:
1.LFW与makeup数据集的单次实验的攻击目标图像都是从LFW中选出的1000张图片中随机选择10张图片进行攻击吗？
2.论文表格1所记录的数值结果都是针对LFW数据集中所选出的1000个目标的平均测试攻击成功率吗？

**Comment by yubangji123** [comment]
1.你可以随机选择10张作为被攻击者
2.是从LFW中选出的100个攻击者和10个被攻击者组成的1000对计算的平均成功率

**Comment by junyizeng** [comment]
非常感谢您的耐心回复。
