### ISSUE TITLE
为什么经过mtcnn对图像对齐和裁剪后，600*600还是报错

### ISSUE THREAD

**Issue by computerAItest** [TencentYoutuResearch/Adv-Makeup#15]
为什么经过mtcnn对图像对齐和裁剪后，600*600还是报错，
File "/home/yuanpeng/桌面/Adv-Makeup-main/dataset.py", line 47, in __getitem__
    before_lmks = self.api_landmarks[before_path].astype(np.int)
KeyError: 'before_aligned_600/00288_0_0.jpg'

**Comment by yubangji123** [comment]
由于文中使用了landmarks对眼部区域进行裁剪，所以你在抠图的时候需要保存成你自己的dict，而代码中的self.api_landmarks这个dict保存的是我原来自己抠的图的landmarks，其中的key和你自己的是不一样的

**Comment by yueanga** [comment]
> 

请问抠图是指要自己确定数据集对应的眼部区域landmarks吗

**Comment by yubangji123** [comment]
是的

**Comment by yueanga** [comment]
请问具体怎么实现呢，./Datasets_Makeup文件夹下有一个landmark_aligned_600.pk文件，是要自己做吗

**Comment by yubangji123** [comment]
这个是我自己实验的数据，你可以用别人的人脸配准工具计算你自己的图的配准点，然后自己抠一下眼睛区域
