### ISSUE TITLE
What's the dataset you have used for training the face recognition models?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [TencentYoutuResearch/Adv-Makeup#17]
Thanks.

**Comment by yubangji123** [comment]
I just pulled the FR models from others' gits. I didn't train them from scratch.

**Comment by GeorgeCarpenter** [comment]
Could you disclose how these models are obtained?

**Comment by GeorgeCarpenter** [comment]
Why is the input image size of facenet different from other pre-trained face models(does the difference in the image sizes affect the adversarial attack performance)?
