### ISSUE TITLE
关于开源代码的复现结果

### ISSUE THREAD

**Issue by wenfs** [TencentYoutuResearch/Adv-Makeup#19]
各位研发人员您好，以下我通过本项目代码以及readme中提供的特征点文件、数据集与模型参数文件的部分生成图像。生成图像在粘贴的部分与原图存在较为明显的颜色差别，自然程度相较于论文结果差一些。请问产生这种现象是否为正常现象或者是可能是代码的使用上哪里出现了问题？
![b32e7682f5c3fddb63a30edb0fe2ad0](https://user-images.githubusercontent.com/48020947/174550371-1ee5980e-c349-4a82-8583-e9fadf2f3913.jpg)
![34254f382887e7ffe43041a39effc3c](https://user-images.githubusercontent.com/48020947/174550473-0d730d35-cbae-4260-a511-f3bf205662bf.jpg)
![85f8276843637c6110c1c9437a68947](https://user-images.githubusercontent.com/48020947/174550499-59d39485-bf47-4ef1-bc35-3523104fb26f.jpg)
![db5f8d12abdc2e6f12bce45111a3cbe](https://user-images.githubusercontent.com/48020947/174550516-af81b1f0-09a1-4fd5-b2be-8ffd8f7789da.jpg)
![6403bc6e098d3307a9e3ef371a15d30](https://user-images.githubusercontent.com/48020947/174550551-78dd5a39-dd28-46fc-9dbb-9e8b579ce150.jpg)

**Comment by yubangji123** [comment]
这里想要完全复现论文中的结果，还需要做个poisson融合的后处理
