### ISSUE TITLE
Is `th_dict [name_of_model][i]` the threshold of  `name_of_model` at 1e-`(i+1)` FAR in the LFW dataset?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [TencentYoutuResearch/Adv-Makeup#20]
Hi.
We think that the [th_dict](https://github.com/TencentYoutuResearch/Adv-Makeup/blob/main/test.py#L11) in the test.py may be the dict of thresholds for different FR models. However, we don't know the calculation method of these thresholds in the dict exactly. Could you tell us is `th_dict [name_of_model][i]` the threshold of  `name_of_model` at 1e-`(i+1)` FAR in the LFW dataset?
Thanks.

**Comment by yubangji123** [comment]
Yes
