### ISSUE TITLE
您好，我在复现论文的时候，看到您与PGD攻击做了对比，论文中是分别对三个白盒模型进行PGD攻击，然后选择黑盒最好的成功率，还是将PGD使用元学习进行了改造。

### ISSUE THREAD

**Issue by SuperCarryFu** [TencentYoutuResearch/Adv-Makeup#21]

**Comment by SuperCarryFu** [comment]
希望您能解答，谢谢您！

**Comment by yubangji123** [comment]
没有元学习改造，因为元学习改造是我们自己提出的方法，所以在对比时没有针对其他对比方法进行相应的改造。

**Comment by SuperCarryFu** [comment]
那是分别针对每个模型使用PGD，然后对成功率加和平均吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月14日(周四) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentYoutuResearch/Adv-Makeup] 您好，我在复现论文的时候，看到您与PGD攻击做了对比，论文中是分别对三个白盒模型进行PGD攻击，然后选择黑盒最好的成功率，还是将PGD使用元学习进行了改造。 (Issue #21)




 
没有元学习改造，因为元学习改造是我们自己提出的方法，所以在对比时没有针对其他对比方法进行相应的改造。

**Comment by yubangji123** [comment]
不是对成功率加平均，而是在每个模型上计算攻击loss，对loss做平均

**Comment by SuperCarryFu** [comment]
嗯嗯，我明白了，十分感谢您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月15日(周五) 上午10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentYoutuResearch/Adv-Makeup] 您好，我在复现论文的时候，看到您与PGD攻击做了对比，论文中是分别对三个白盒模型进行PGD攻击，然后选择黑盒最好的成功率，还是将PGD使用元学习进行了改造。 (Issue #21)




 
不是对成功率加平均，而是在每个模型上计算攻击loss，对loss做平均

**Comment by luvWY** [comment]
能不能针对adv-makeup交流一下呀
