### ISSUE TITLE
您好，请问before_orig, before_pasted, target_img, fake_afters, before_pasted_eyes分别代表什么含义？

### ISSUE THREAD

**Issue by HeBangYan** [TencentYoutuResearch/Adv-Makeup#22]
非常感谢大佬的开源：）

想请问一下，您在[paste_patch](https://github.com/TencentYoutuResearch/Adv-Makeup/blob/f238d37bb3e2a13deef0f0270f6ea7c1be005d5a/model.py#L159)函数里定义了before_orig, before_pasted, target_img, fake_afters, before_pasted_eyes这五个数组，请问分别有什么含义呀？

**Comment by yubangji123** [comment]
这些都是不同的图，你可以把它们保存成图片然后查看

**Comment by HeBangYan** [comment]
谢谢大佬！
