### ISSUE TITLE
Random selection of meta-train models during training

### ISSUE THREAD

**Issue by Werty18** [TencentYoutuResearch/Adv-Makeup#23]
Hi, in paper it has been mentioned that the models will be selected randomly during meta learning (training phase). However, in model.py file, in line 264, only the first 2 models is selected every time as meta train models. Should not it be random from 3 models?

**Comment by yubangji123** [comment]
This is just a training strategy in meta-learning, either you can randomly select models or select first 2 models for every iteration, which all depends on you. Note that, we keep a queue to ensure the variance of each selection in our implementation.
