### ISSUE TITLE
What are the 106 landmarks?

### ISSUE THREAD

**Issue by njuaplusplus** [TencentYoutuResearch/Adv-Makeup#26]
Thank you for open-sourcing this. 

Because there is no landmark detection code here, it's difficult to directly apply this attack with real images.

The eye regions are created by indexing the landmarks array. But there are no instructions on the correspondence between the index and the physical meaning of the point. This makes utilizing other existing landmark detection methods difficult.

Could you tell me the relation between the index and the meaning of the point? For example, what does the 94th point in the landmarks mean, left_eye_left_corner, right_eye_top, or something else?

Thank you very much.

**Comment by njuaplusplus** [comment]
I found the index-name relation here: 
https://github.com/georgegu1997/makeup-transfer-public/blob/master/src/api_util.py#L14

**Comment by yubangji123** [comment]
I think you don't have to worry about this. There are no  special correlations between the index and the meaning of the point. By using other landmark detection approaches, you can draw the landmark points on the face images with any different index orders. It would not sway your selection of the semantic facial regions according to the landmarks.

**Comment by njuaplusplus** [comment]
Thank you for your reply. Actually, we need to give the correct indices because in [the code](https://github.com/TencentYoutuResearch/Adv-Makeup/blob/main/model.py#L185-L194) the orbital area is selected using the indices.

**Comment by yubangji123** [comment]
其实你可以自己去选择这个orbital area，不一定非要按照这里给出的索引来。用一个其他的landmark检测器，然后画一下，大致看看围绕眼睛区域的是哪些landmarks，然后挑选出来就行了。

**Comment by njuaplusplus** [comment]
谢谢您回复。是可以这样的。
