### ISSUE TITLE
关于物理实现的一些问题

### ISSUE THREAD

**Issue by junyizeng** [TencentYoutuResearch/Adv-Makeup#27]
研发人员您好，非常感谢您开源Adv-makeup这一项目，关于论文中物理实验的部分，我有一些问题想请教：
1.请问您所承载对抗眼影的纹身贴纸是自己打印的还是第三方纹身贴纸店铺代为制作？如果是后者能否提供一下店铺信息？
2.请问纹身贴纸是直接按照数字图像修改的区域直接使用，还是在得到原板后对要实际使用区域进行裁剪？
3.在查看您的实验结果时发现您的物理妆容离眼镜边缘较远，而数字结果的妆容一直画到了眼白与眼眶的边缘，请问是您是在物理实现时修改了mask改变了对应数字对抗样本的化妆区域还是其他？
我承诺我的物理条件复现实验只在实验室环境内进行，不会使用在任何实际场景，希望您能不吝赐教。
再次感谢您进行这项有意义的工作并将其开源。

**Comment by njuaplusplus** [comment]
I have the exact same questions. Could you please provide the details? Thanks a lot! @yubangji123

**Comment by yubangji123** [comment]
1、这是在淘宝店找的商家，因为时间比较久了，所以不太好问到具体的店铺信息了。
2、这个是把内容通过纹身贴纸制作出来以后，裁剪有对抗信息的区域，然后贴回到人脸上测试。
3、物理场景复现，还是会比较困难，不太容易完全把数字图像的攻击复现出来，因此我们在裁剪的时候，没有完全按照数字图像的方式来。
