### ISSUE TITLE
关于在Face++测试结果的一些疑问

### ISSUE THREAD

**Issue by junyizeng** [TencentYoutuResearch/Adv-Makeup#28]
您好，下面两张图的最后一列图像是我使用开源项目针对对应目标生成的妆容对抗样本。我发现相对于论文中展示的结果，我所生成的妆容对抗样本Face++的置信度普遍偏低。有两张图像的置信度差距较为明显，请问是将对抗样本上传到face++时进行了预处理？还是一些细节出现问题？是否能提供face++检测对应的代码？

![5%8{RM_R`O7`WTNYE8QBG%N](https://user-images.githubusercontent.com/80525097/220321596-f8b91a94-122e-4edd-a9a5-565a99a4d043.png)

![Y2U@4AR~UPJ24@63%915`)1](https://user-images.githubusercontent.com/80525097/220321639-f276fc4b-9b35-45a3-9fad-a321370e4a76.png)

**Comment by yubangji123** [comment]
这个攻击彩妆是一边训练一边生成的，生成的质量不同，可能会出现部分人脸的置信度不高的情况，如果你要高置信度，可以把攻击损失权重稍微调整高一点也可以。此外，彩妆攻击对于男性效果会不太稳定。

**Comment by junyizeng** [comment]
感谢您的回答！我可以理解为您是保存了训练中的生成的彩妆图像进行的face++的检测吗？但是一般来讲应该是模型训练结束后再进行模型的各项指标的测试。如果我的理解没有问题的话，请问您为何要这样进行测试？我不是很明白。

**Comment by yubangji123** [comment]
彩妆攻击的主要目的还是生成带有对抗性的彩妆，训练过程就是生成过程，就跟PGD、FGSM这些方法一样，训练完成，对抗样本也就生成完了。

**Comment by junyizeng** [comment]
好的，感谢回复！那请问论文所展示的结果是训练300步(开源项目的最大训练步长)的生成器所生成的妆容图像吗？所使用的白盒替代模型是哪一些呢?为了进一步对齐论文实验设置，如果可以的话是否能提供一下所选的100张素颜图像的具体信息呢？

**Comment by yubangji123** [comment]
分别回答一下你的问题：
1、论文展示的就是300步的步长
2、白盒替代模型文章中应该有描述，是IR152, IRSE50, MobileFace，Facenet四个模型当中，每次随机选三个作为白盒模型，剩下的一个用于黑盒迁移性的评估
3、这一百张素颜原图你可以任选，不一定要跟我这边一样，你可以在你自选的100张图上进行对比实验，结果是可信的就行

**Comment by junyizeng** [comment]
感谢您的回答！但是按照论文描述的话，根据选取黑盒评估的模型不同，就会产生4种模型选择条件下训练出来的生成器模型，请问您具体使用哪一个条件下训练的模型的呢？目前我直接使用开源项目测试出的结果就如上图，有部分样本的置信度结果相差还是较大的，因此我不知道这一结果是否能佐证我的代码复现没有问题。并且我在使用face++进行对应的原图与目标图像时发现置信度结果会比论文的结果高一些，因此我想统一一下其他变量确定我的代码复现是没问题的，如果可以的话能否提供提供一下face++的测试代码呢？

**Comment by yubangji123** [comment]
这样吧，我们加个v聊一下？

**Comment by junyizeng** [comment]
不好意思，之前处理别的事情了，没有及时回复。那麻烦您提供一下微信？或者您加我，我的v是18828870777，id名：egoist。
