### ISSUE TITLE
How to generate the landmarks?

### ISSUE THREAD

**Issue by zhoufengfan** [TencentYoutuResearch/Adv-Makeup#3]
We would like to generate the landmarks of our face images.

We see that a `numpy.ndarray` in `landmark_aligned_600.pk` contains 106 2D points. However, we can only generate 5 2D points using `mtcnn`. Could the authors add the code of generating the landmarks in the repo or describe how to generate the landmarks?

Thanks.

**Comment by yubangji123** [comment]
Hi,

This work is funded by Tencent, I have no right to release other materials. You can refer to some face alignment works.

Thanks

**Comment by zhoufengfan** [comment]
We will refer to other face alignment works.

**Comment by RainbowXie** [comment]
Hi, did you generated the landmarks? Could you please gave me any hints?
