### ISSUE TITLE
ModuleNotFoundError: No module named 'Pretrained_FR_Models'

### ISSUE THREAD

**Issue by vajic** [TencentYoutuResearch/Adv-Makeup#5]
你好，
     麻烦问一下，如何获取Pretrained_FR_Models 这个模块，这个模块无法找到。查询网上的资料也没有获取到相关信息，是私有模块吗？

**Comment by vajic** [comment]
找到了，在README里面有说明，地址是这个：https://drive.google.com/drive/folders/1G_2R_7XQhzzMQdEhph0ZI7dV4sGYjjzu

**Comment by ljzology** [comment]
能发我一份吗，我这里上不了外网。ljzology@163.com
多谢
