### ISSUE TITLE
没发现内容损失的实现

### ISSUE THREAD

**Issue by SuperCarryFu** [TencentYoutuResearch/Adv-Makeup#7]
您好，我在代码中似乎没有看到论文中内容损失的实现？并且多了一个用于去噪的tv_loss，二者的作用是相似的吗？

**Comment by yubangji123** [comment]
有一个loss使用了VGG模型提取特征，那个就是内容损失

**Comment by SuperCarryFu** [comment]
很感谢您的解答，再次感谢!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月18日(周五) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentYoutuResearch/Adv-Makeup] 没发现内容损失的实现 (Issue #7)




 
有一个loss使用了VGG模型提取特征，那个就是内容损失
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
