### ISSUE TITLE
数字攻击的实验设置

### ISSUE THREAD

**Issue by junyizeng** [TencentYoutuResearch/Adv-Makeup#8]
由于在复现论文实验效果中遇到一些问题，想请教各位研发人员以下一些问题:
1.请问在使用LFW数据集进行训练时，用于输入判别器的妆容图像是使用的makeup数据集中妆容图像吗？
2.使用makeup数据集进行训练的素颜图像是数据集中剔除100张与10张作为有目标攻击的图片后剩下的图片吗？
2.论文中选择出的198张妆容图像是如何选择的？

**Comment by yubangji123** [comment]
1.使用的是同样的妆容图像，不过这个可以根据你自己的需求来修改，不过LFW分辨率很低，视觉效果不太好，还是建议使用高清图像
2.素颜图就是100张攻击者用于训练对抗彩妆的生成器，剩余的10张是被攻击者
3.198张带妆图像主要选择的依据是眼妆比较浓的，这样生成的对抗彩妆视觉效果会比较好

**Comment by junyizeng** [comment]
好的，非常感谢您的解答。

**Comment by junyizeng** [comment]
还有一些想要请教的问题:
1.在论文中，基于预训练的vgg16模型分别计算了风格损失与内容损失，但是在代码上并没有看到内容损失相关的部分。
2.代码中并没有meta-learning中random select相关的部分。

**Comment by junyizeng** [comment]
还有一些想要请教的问题:
1.在论文中，基于预训练的vgg16模型分别计算了风格损失与内容损失，但是在代码上并没有看到内容损失相关的部分。
2.代码中并没有meta-learning中random select相关的部分。
3.是使用的makeup数据集中剩余的图像作为测试集测试模型的攻击效果吗？

**Comment by yubangji123** [comment]
1.cont的loss其实可加可不加，和style效果类似，加了视觉效果会有略微的提升
2.没有做随机选取，这里主要是换了下顺序，每次迭代把第一个放到末尾，类似队列那种
3.因为做的是模型迁移攻击，所以黑盒迁移性测试的时候还是用的训练的那100张图，训练好的对抗彩妆生成器也可以对没见过的图来生成彩妆，不过这样生成的攻击性会下降。
上述你都可以根据自己的需求来修改

**Comment by junyizeng** [comment]
好的，非常感谢您的解答。

**Comment by junyizeng** [comment]
研发人员您好，在复现文中的数字攻击的实验一时对实验一中的实验设置有一些疑惑，想请教以下问题:
1.LFW与makeup数据集的攻击目标图像都是从LFW中选出的1000张图片中随机选择10张图片进行攻击吗？
2.论文表格1所记录的数值结果都是针对LFW数据集中所选出的1000个目标的平均测试攻击成功率吗？
