### ISSUE TITLE
Evaluation on my own images 

### ISSUE THREAD

**Issue by andreibezborodov** [TencentYoutuResearch/Adv-Makeup#9]
Hello!

Thank you for great work!
I would like to know if it is possible to conduct experiments with trained models on your own images. If so, how to generate landmarks?

**Comment by yubangji123** [comment]
You can find everything from here: https://github.com/wangguanzhi/LADN
All the images preseneted in the paper is originally from this git.

**Comment by andreibezborodov** [comment]
> You can find everything from here: https://github.com/wangguanzhi/LADN All the images preseneted in the paper is originally from this git.

Thank you for answering! Seems that I have to use Face++ Detect API in order to generate `landmark.pk` file with landmarks for new faces.
